### ISSUE TITLE
Diversa visualizzazione

### ISSUE THREAD

**Issue by FabioCavazziniITI** [ITI-TV/TV_ITI-TV_2.0#7]
Vi comunico che tra l'anteprima e la visualizzazione nella TV mi sono trovato con del testo che andava a capo senza la presenza di <br>. Nell'anteprima andava tutto bene (il codice era correttamente eseguito), solo nella tv era diverso.
![WhatsApp Image 2024-11-05 at 12 27 36](https://github.com/user-attachments/assets/52b7461b-5ca9-45e2-9e2f-de3707258228)
![WhatsApp Image 2024-11-05 at 12 37 40](https://github.com/user-attachments/assets/3902f7ae-bc69-42b9-8b9a-dec67003d45f)

**Comment by ZELA2000** [comment]
Sistemato il bug, in questi giorni procedo con il caricamento dell'aggiornamento sul server
